name: docs-deploy

on:
  push:
    branches:
      - main

permissions:
  # Used to push the docs to the `gh-pages` branch.
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y roffit

      - name: docs
        run: |
          mkdir public
          roffit < eatmynetwork.1 > public/index.html

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
